name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

    - name: Log in to Google Artifact Registry
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ethanwebcraft

    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker europe-docker.pkg.dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: europe-docker.pkg.dev/ethanwebcraft/imf/smart-html:${{ steps.slug.outputs.sha7 }}
